CC=g++

all: pancake sliding

pancake: pancakePuzzleTest.cpp 
	$(CC) -g -std=c++11 pancakePuzzleTest.cpp -o pancakeTest

sliding: slidingPuzzleTest.cpp 
	$(CC) -g -std=c++11 slidingPuzzleTest.cpp -o slidingPuzzleTest
	
clean:
	rm -f pancakeTest slidingPuzzleTest
