CC=g++

all:  sliding tree

: PuzzleTest.cpp 
	$(CC) -g -std=c++11 PuzzleTest.cpp -o Test

sliding: slidingPuzzleTest.cpp 
	$(CC) -g -std=c++11 slidingPuzzleTest.cpp -o slidingPuzzleTest

tree: treeTest.cpp 
	$(CC) -g -std=c++11 treeTest.cpp -o treeTest
	
clean:
	rm -f Test slidingPuzzleTest treeTest
